def content(filename, timestamp):
    return (f""
        f"---\n"
        f"title: {filename}\n"
        f"creation: {timestamp}\n"
        f"tags: \n"
        f"---\n"
        f"\n"
        f"# {filename}\n"
        f"\n"
        f"\n"
        f"\n"
        f"---\n"
        f"# Links & References\n"
        f"\n"
        f"- \n"
        f"\n"
        f"---\n"
    )
