#!/usr/bin/python3

print()
print("Vinotes - External Note-Taking utility for Neovim.")
print()
print("command           -                    description")
print()
print("deactivate        -   Exit the Vinotes Environment")
print()
print("changelog         -          View latest version's")
print("                             changelog")
print()
print("conf              -    Edit Vinotes configuration.")
print()
print("reload or rl      -   Reload Principle directories")
print("                      and templates.")
print()
print("update            -     Update Utils and Binaries.")
print()
print("create-note or cn -             Create a new note.")
print("- usage: vinotes create-note <path/to/file>")
print()
print("open-daily or od  -          Opens the daily note.")
print("- usage: vinotes open-daily")
print()
print("open-note or on   -        Opens any created note.")
print("- usage: vinotes open-note")
print("         vinotes open-note <filepath>")
print()
print("--help or -h      -          Opens this help menu.")
